<#
.SYNOPSIS
    MellyTrade Desktop Launcher - build/check wrapper.

.DESCRIPTION
    Checks prerequisites for building the desktop launcher EXE and, when
    -Build is explicitly requested, runs PyInstaller to produce a local
    single-file executable.

    Safety reminder:
      launcher is local-only
      no live trading
      no broker execution
      dry-run/read-only posture preserved

    IMPORTANT - do NOT commit generated artifacts:
      dist/           <- generated by PyInstaller -Build
      build/          <- generated by PyInstaller -Build
      *.spec          <- generated by PyInstaller -Build
    Add to .gitignore if not already present before running -Build.

.PARAMETER CheckOnly
    Verify prerequisites only. No files are created. (Default mode.)

.PARAMETER Build
    Run PyInstaller to produce dist/MellyTradeLauncher.exe.
    Only runs if PyInstaller is available.
    Generated artifacts (dist/, build/, *.spec) must NOT be committed.

.EXAMPLE
    .\scripts\build_desktop_launcher.ps1 -CheckOnly
    .\scripts\build_desktop_launcher.ps1 -Build

#>

[CmdletBinding(DefaultParameterSetName = 'CheckOnly')]
param(
    [Parameter(ParameterSetName = 'CheckOnly')]
    [switch]$CheckOnly,

    [Parameter(ParameterSetName = 'Build')]
    [switch]$Build
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ---------------------------------------------------------------------------
# Resolve paths
# ---------------------------------------------------------------------------

$ScriptDir  = $PSScriptRoot
$RepoRoot   = Resolve-Path (Join-Path $ScriptDir "..")
$LauncherPy = Join-Path $ScriptDir "desktop_launcher.py"

# ---------------------------------------------------------------------------
# Safety banner
# ---------------------------------------------------------------------------

Write-Host ""
Write-Host "======================================================"
Write-Host "  MellyTrade Desktop Launcher Build/Check Wrapper"
Write-Host "======================================================"
Write-Host "  SAFETY: launcher is local-only"
Write-Host "  SAFETY: no live trading"
Write-Host "  SAFETY: no broker execution"
Write-Host "  SAFETY: dry-run/read-only posture preserved"
Write-Host "======================================================"
Write-Host ""

if ($Build) {
    Write-Host "[MODE] Build - will run PyInstaller if available."
    Write-Host "[WARN] Generated artifacts (dist/, build/, *.spec) must NOT be committed."
    Write-Host "       Ensure dist/, build/, and *.spec are in .gitignore before proceeding."
    Write-Host ""
} else {
    Write-Host "[MODE] CheckOnly - no files will be created or modified."
    Write-Host ""
}

# ---------------------------------------------------------------------------
# Step 1 - Verify launcher script exists
# ---------------------------------------------------------------------------

Write-Host "[CHECK] desktop_launcher.py ..."
if (Test-Path $LauncherPy) {
    Write-Host "  [PASS] Found: $LauncherPy"
} else {
    Write-Host "  [FAIL] Not found: $LauncherPy"
    Write-Host "         Run this script from the repo root after creating scripts/desktop_launcher.py"
    exit 1
}

# ---------------------------------------------------------------------------
# Step 2 - Verify Python 3.11 is available
# ---------------------------------------------------------------------------

Write-Host "[CHECK] Python 3.11 ..."
try {
    $pyVersion = & py -3.11 --version 2>&1
    Write-Host "  [PASS] $pyVersion"
} catch {
    Write-Host "  [FAIL] 'py -3.11' is not available."
    Write-Host "         Install Python 3.11 from https://python.org and ensure the"
    Write-Host "         Python Launcher for Windows is installed."
    exit 1
}

# ---------------------------------------------------------------------------
# Step 3 - Check PyInstaller availability
# ---------------------------------------------------------------------------

Write-Host "[CHECK] PyInstaller ..."
$pyInstallerAvailable = $false
try {
    $piVersion = & py -3.11 -m PyInstaller --version 2>&1
    if ($LASTEXITCODE -eq 0) {
        $pyInstallerAvailable = $true
        Write-Host "  [PASS] PyInstaller $piVersion"
    } else {
        Write-Host "  [SKIP] PyInstaller not available (exit code $LASTEXITCODE)."
    }
} catch {
    Write-Host "  [SKIP] PyInstaller not available."
}

if (-not $pyInstallerAvailable) {
    Write-Host ""
    Write-Host "  PyInstaller is not installed. To install it (local dev only):"
    Write-Host "    py -3.11 -m pip install pyinstaller"
    Write-Host ""
    Write-Host "  After installing, re-run:"
    Write-Host "    .\scripts\build_desktop_launcher.ps1 -CheckOnly"
    Write-Host "  Or to build:"
    Write-Host "    .\scripts\build_desktop_launcher.ps1 -Build"
    Write-Host ""
    if ($Build) {
        Write-Host "[SKIPPED] Cannot build without PyInstaller. Install it first."
        exit 0
    }
}

# ---------------------------------------------------------------------------
# CheckOnly - summary and exit
# ---------------------------------------------------------------------------

if (-not $Build) {
    Write-Host ""
    Write-Host "======================================================"
    Write-Host "  CheckOnly complete."
    if ($pyInstallerAvailable) {
        Write-Host "  All prerequisites met. To build:"
        Write-Host "    .\scripts\build_desktop_launcher.ps1 -Build"
    } else {
        Write-Host "  Python OK. PyInstaller missing - install and retry."
        Write-Host "    py -3.11 -m pip install pyinstaller"
    }
    Write-Host "======================================================"
    Write-Host ""
    exit 0
}

# ---------------------------------------------------------------------------
# Build - run PyInstaller (only reached when -Build is explicitly passed
#         and PyInstaller is available)
# ---------------------------------------------------------------------------

Write-Host ""
Write-Host "[BUILD] Running PyInstaller ..."
Write-Host "  Output: dist/MellyTradeLauncher.exe"
Write-Host "  REMINDER: dist/, build/, and *.spec must NOT be committed."
Write-Host ""

Set-Location $RepoRoot

& py -3.11 -m PyInstaller `
    --onefile `
    --name MellyTradeLauncher `
    (Join-Path "scripts" "desktop_launcher.py")

if ($LASTEXITCODE -ne 0) {
    Write-Host ""
    Write-Host "[FAIL] PyInstaller exited with code $LASTEXITCODE"
    Write-Host "       Review the output above for errors."
    exit $LASTEXITCODE
}

$DistDir = Join-Path $RepoRoot "dist"
$ExePath = Join-Path $DistDir "MellyTradeLauncher.exe"
if (Test-Path $ExePath) {
    Write-Host ""
    Write-Host "======================================================"
    Write-Host "  [PASS] Build complete."
    Write-Host "  EXE:  $ExePath"
    Write-Host ""
    Write-Host "  REMINDER: Do NOT commit these generated artifacts:"
    Write-Host "    dist/"
    Write-Host "    build/"
    Write-Host "    MellyTradeLauncher.spec"
    Write-Host ""
    Write-Host "  SAFETY: launcher is local-only"
    Write-Host "  SAFETY: no live trading"
    Write-Host "  SAFETY: no broker execution"
    Write-Host "  SAFETY: dry-run/read-only posture preserved"
    Write-Host "======================================================"
    Write-Host ""
} else {
    Write-Host "[WARN] EXE not found at expected path: $ExePath"
    Write-Host "       Check PyInstaller output above."
}
